# Generated by Django 5.0.4 on 2024-05-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buynow',
            new_name='buynow_1',
        ),
    ]
