# Generated by Django 5.0.4 on 2024-05-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_buynow_buynow_1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buynow_1',
            new_name='buy',
        ),
    ]
