# Generated by Django 5.0.4 on 2024-05-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_buynow_1_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='buyNow',
            new_name='buynow',
        ),
    ]
