# Generated by Django 5.0.4 on 2024-05-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_buy_amount_alter_buy_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='buynow',
            new_name='buy',
        ),
    ]
